# Generated by Django 4.2.7 on 2024-04-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("in Progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="registered",
                max_length=20,
            ),
        ),
    ]
