# Generated by Django 4.2.7 on 2024-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("reason", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("division", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("priority", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Registered", "Registered"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Registered",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
